In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset_dir = '../datasets/seznam'

In [3]:
client = pd.read_parquet(f'{dataset_dir}/data/client.pqt')
dobito = pd.read_parquet(f'{dataset_dir}/data/dobito.pqt')
probehnuto_mimo_penezenku = pd.read_parquet(f'{dataset_dir}/data/probehnuto_mimo_penezenku.pqt')
probehnuto = pd.read_parquet(f'{dataset_dir}/data/probehnuto.pqt')

In [4]:
dobito

        client_id       date sluzba  kc_dobito
554345    8674551 2012-08-01      g    6280.00
520984    1027825 2012-08-01      g   37680.00
520983     902502 2012-08-01      g    3768.00
520982    1161708 2012-08-01      g   31400.00
520981      78514 2012-08-01      g   18840.00
...           ...        ...    ...        ...
21038     9674695 2015-10-01      a    5187.28
256653      23696 2015-10-01      d   77850.02
33980     9773761 2015-10-01      a    1296.82
139829    8672560 2015-10-01      h    2593.64
471629     105735 2015-10-01      e   10377.70

[554096 rows x 4 columns]

In [5]:
# generate a mapping from dobito.index to a unique id
dobito_id = np.arange(len(dobito))
dobito_id_map = pd.Series(dobito_id, index=dobito.index)
dobito['dobito_id'] = dobito_id_map

In [6]:
dobito

        client_id       date sluzba  kc_dobito  dobito_id
554345    8674551 2012-08-01      g    6280.00          0
520984    1027825 2012-08-01      g   37680.00          1
520983     902502 2012-08-01      g    3768.00          2
520982    1161708 2012-08-01      g   31400.00          3
520981      78514 2012-08-01      g   18840.00          4
...           ...        ...    ...        ...        ...
21038     9674695 2015-10-01      a    5187.28     554091
256653      23696 2015-10-01      d   77850.02     554092
33980     9773761 2015-10-01      a    1296.82     554093
139829    8672560 2015-10-01      h    2593.64     554094
471629     105735 2015-10-01      e   10377.70     554095

[554096 rows x 5 columns]

In [7]:
charge_train = pd.read_parquet(f'{dataset_dir}/charge/train.pqt')
charge_validation = pd.read_parquet(f'{dataset_dir}/charge/validation.pqt')
charge_test = pd.read_parquet(f'{dataset_dir}/charge/test.pqt')

In [8]:
charge_train

        client_id       date sluzba  kc_dobito
554345    8674551 2012-08-01      g    6280.00
520984    1027825 2012-08-01      g   37680.00
520983     902502 2012-08-01      g    3768.00
520982    1161708 2012-08-01      g   31400.00
520981      78514 2012-08-01      g   18840.00
...           ...        ...    ...        ...
511802     107291 2015-04-01      e   10377.70
418711    9696717 2015-04-01      d  250939.38
253523    9787393 2015-04-01      d   18840.00
256377      85339 2015-04-01      h   23355.32
418041    9787908 2015-04-01      d    6280.00

[443276 rows x 4 columns]

In [9]:
# update charge train
charge_train['dobito_id'] = charge_train.index.map(dobito_id_map)

# update charge validation
charge_validation['dobito_id'] = charge_validation.index.map(dobito_id_map)

# update charge test
charge_test['dobito_id'] = charge_test.index.map(dobito_id_map)

In [10]:
charge_train

        client_id       date sluzba  kc_dobito  dobito_id
554345    8674551 2012-08-01      g    6280.00          0
520984    1027825 2012-08-01      g   37680.00          1
520983     902502 2012-08-01      g    3768.00          2
520982    1161708 2012-08-01      g   31400.00          3
520981      78514 2012-08-01      g   18840.00          4
...           ...        ...    ...        ...        ...
511802     107291 2015-04-01      e   10377.70     443271
418711    9696717 2015-04-01      d  250939.38     443272
253523    9787393 2015-04-01      d   18840.00     443273
256377      85339 2015-04-01      h   23355.32     443274
418041    9787908 2015-04-01      d    6280.00     443275

[443276 rows x 5 columns]

In [24]:
probehnuto = pd.read_parquet(f'{dataset_dir}/data/probehnuto.pqt')
probehnuto

         client_id       date sluzba  kc_proklikano
811592     9722487 2012-08-01   None          12.56
1446900     109705 2012-08-01      e       20510.48
1446901      81250 2012-08-01      e       16117.62
1446902     107927 2012-08-01      e        2392.68
1446903     104343 2012-08-01      e        4154.22
...            ...        ...    ...            ...
44844         8644 2015-10-01      a       15615.22
44843        12652 2015-10-01      a        4452.52
44842         7270 2015-10-01      a        5099.36
108997       58094 2015-10-01      a        1070.74
1462077     946957 2015-10-01   None         153.86

[1461749 rows x 4 columns]

In [29]:
probehnuto_id = np.arange(len(probehnuto))
probehnuto_id_map = pd.Series(probehnuto_id, index=probehnuto.index)
probehnuto['probehnuto_id'] = probehnuto_id_map

probehnuto

         client_id       date sluzba  kc_proklikano  probehnuto_id
811592     9722487 2012-08-01   None          12.56              0
1446900     109705 2012-08-01      e       20510.48              1
1446901      81250 2012-08-01      e       16117.62              2
1446902     107927 2012-08-01      e        2392.68              3
1446903     104343 2012-08-01      e        4154.22              4
...            ...        ...    ...            ...            ...
44844         8644 2015-10-01      a       15615.22        1461744
44843        12652 2015-10-01      a        4452.52        1461745
44842         7270 2015-10-01      a        5099.36        1461746
108997       58094 2015-10-01      a        1070.74        1461747
1462077     946957 2015-10-01   None         153.86        1461748

[1461749 rows x 5 columns]

In [26]:
prepay_train = pd.read_parquet(f'{dataset_dir}/prepay/train.pqt')
prepay_validation = pd.read_parquet(f'{dataset_dir}/prepay/validation.pqt')
prepay_test = pd.read_parquet(f'{dataset_dir}/prepay/test.pqt')

In [30]:
prepay_train['probehnuto_id'] = prepay_train.index.map(probehnuto_id_map)
prepay_validation['probehnuto_id'] = prepay_validation.index.map(probehnuto_id_map)
prepay_test['probehnuto_id'] = prepay_test.index.map(probehnuto_id_map)

prepay_train
prepay_validation
prepay_test

        client_id       date sluzba  kc_proklikano  probehnuto_id
203034      84977 2015-07-01      a        1456.96        1316027
203035    1124562 2015-07-01      a         973.40        1316028
882225    2695957 2015-07-01      d          25.12        1316029
882226     982156 2015-07-01      d           6.28        1316030
882227     112736 2015-07-01      d         659.40        1316031
...           ...        ...    ...            ...            ...
44845     8865077 2015-10-01      a       15640.34        1461743
44844        8644 2015-10-01      a       15615.22        1461744
44843       12652 2015-10-01      a        4452.52        1461745
44842        7270 2015-10-01      a        5099.36        1461746
108997      58094 2015-10-01      a        1070.74        1461747

[143953 rows x 5 columns]

In [33]:
probehnuto_mimo_penezenku = pd.read_parquet(f'{dataset_dir}/data/probehnuto_mimo_penezenku.pqt')

In [34]:
probehnuto_mimo_penezenku

        client_id       date probehla_inzerce_mimo_penezenku
0            3901 2012-08-01                             ANO
348450      99523 2012-08-01                             ANO
348430      99521 2012-08-01                             ANO
348414      99517 2012-08-01                             ANO
50618       14536 2012-08-01                             ANO
...           ...        ...                             ...
426786     937998 2015-10-01                             ANO
426665     937324 2015-10-01                             ANO
34444       10853 2015-10-01                             ANO
33966       10713 2015-10-01                             ANO
599385    9805032 2015-10-01                             ANO

[599386 rows x 3 columns]

In [35]:
probehnuto_mimo_penezenku_id = np.arange(len(probehnuto_mimo_penezenku))
probehnuto_mimo_penezenku_id_map = pd.Series(probehnuto_mimo_penezenku_id, index=probehnuto_mimo_penezenku.index)
probehnuto_mimo_penezenku['probehnuto_mimo_penezenku_id'] = probehnuto_mimo_penezenku_id_map

probehnuto_mimo_penezenku

,client_id,date,probehla_inzerce_mimo_penezenku,probehnuto_mimo_penezenku_id
0,3901,2012-08-01,ANO,0
348450,99523,2012-08-01,ANO,1
348430,99521,2012-08-01,ANO,2
348414,99517,2012-08-01,ANO,3
50618,14536,2012-08-01,ANO,4
...,...,...,...,...
426786,937998,2015-10-01,ANO,599381
426665,937324,2015-10-01,ANO,599382
34444,10853,2015-10-01,ANO,599383
33966,10713,2015-10-01,ANO,599384
599385,9805032,2015-10-01,ANO,599385

In [37]:
# Save the parquet files under griffin_dataset
griffin_dataset_path = '../griffin_datasets/seznam-griffin-pk'
dataset_path = dataset_dir
import shutil
import os
shutil.rmtree(griffin_dataset_path, ignore_errors=True)
shutil.copytree(dataset_path, griffin_dataset_path)

'../griffin_datasets/seznam-griffin-pk'

In [38]:
# resave the parquet files
dobito.to_parquet(f'{griffin_dataset_path}/data/dobito.pqt')
probehnuto.to_parquet(f'{griffin_dataset_path}/data/probehnuto.pqt')
probehnuto_mimo_penezenku.to_parquet(f'{griffin_dataset_path}/data/probehnuto_mimo_penezenku.pqt')
charge_train.to_parquet(f'{griffin_dataset_path}/charge/train.pqt')
charge_validation.to_parquet(f'{griffin_dataset_path}/charge/validation.pqt')
charge_test.to_parquet(f'{griffin_dataset_path}/charge/test.pqt')
prepay_train.to_parquet(f'{griffin_dataset_path}/prepay/train.pqt')
prepay_validation.to_parquet(f'{griffin_dataset_path}/prepay/validation.pqt')
prepay_test.to_parquet(f'{griffin_dataset_path}/prepay/test.pqt')

In [39]:
# test the parquet files
dobito_new = pd.read_parquet(f'{griffin_dataset_path}/data/dobito.pqt')
dobito_new

        client_id       date sluzba  kc_dobito  dobito_id
554345    8674551 2012-08-01      g    6280.00          0
520984    1027825 2012-08-01      g   37680.00          1
520983     902502 2012-08-01      g    3768.00          2
520982    1161708 2012-08-01      g   31400.00          3
520981      78514 2012-08-01      g   18840.00          4
...           ...        ...    ...        ...        ...
21038     9674695 2015-10-01      a    5187.28     554091
256653      23696 2015-10-01      d   77850.02     554092
33980     9773761 2015-10-01      a    1296.82     554093
139829    8672560 2015-10-01      h    2593.64     554094
471629     105735 2015-10-01      e   10377.70     554095

[554096 rows x 5 columns]

dataset_name: Seznam
tables:
  - name: Client
    source: data/client.pqt
    format: parquet
    columns:
      - name: client_id
        dtype: primary_key
      - name: kraj
        dtype: category
      - name: obor
        dtype: category
  - name: Dobito
    source: data/dobito.pqt
    format: parquet
    columns:
      - name: dobito_id
        dtype: primary_key
      - name: client_id
        dtype: foreign_key
        link_to: Client.client_id
      - name: date
        dtype: datetime
      - name: sluzba
        dtype: category
      - name: kc_dobito
        dtype: float
    time_column: date
  - name: Probehnuto
    source: data/probehnuto.pqt
    format: parquet
    columns:
      - name: probehnuto_id
        dtype: primary_key
      - name: client_id
        dtype: foreign_key
        link_to: Client.client_id
      - name: date
        dtype: datetime
      - name: sluzba
        dtype: category
      - name: kc_proklikano
        dtype: float
    time_column: date
  - name: ProbehnutoMimoPenezenku
    source: data/probehnuto_mimo_penezenku.pqt
    format: parquet
    columns:
      - name: probehnuto_mimo_penezenku_id
        dtype: primary_key
      - name: client_id
        dtype: foreign_key
        link_to: Client.client_id
      - name: date
        dtype: datetime
      - name: probehla_inzerce_mimo_penezenku
        dtype: category
    time_column: date
tasks:
  - name: charge
    source: charge/{split}.pqt
    format: parquet
    columns:
      - name: dobito_id
        dtype: primary_key
      - name: client_id
        dtype: foreign_key
        link_to: Client.client_id
      - name: date
        dtype: datetime
      - name: sluzba
        dtype: category
      - name: kc_dobito
        dtype: float
    time_column: date
    evaluation_metric: accuracy
    target_column: sluzba
    target_table: Dobito
    task_type: classification
  - name: prepay
    source: prepay/{split}.pqt
    format: parquet
    columns:
      - name: probehnuto_id
        dtype: primary_key
      - name: client_id
        dtype: foreign_key
        link_to: Client.client_id
      - name: date
        dtype: datetime
      - name: sluzba
        dtype: category
      - name: kc_proklikano
        dtype: float
    time_column: date
    evaluation_metric: accuracy
    target_column: sluzba
    target_table: Probehnuto
    task_type: classification