In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
data_dir = Path('../datasets/outbrain-small')
griffin_data_dir = Path('../griffin_datasets/outbrain-small-pk')

In [3]:
clicks = pd.read_parquet(data_dir / 'data' / 'clicks.pqt')
print(clicks.shape)
clicks

(87142, 4)

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
0                            54  229333        0 2016-06-14 04:00:03.786
1                           668  211425        0 2016-06-14 04:00:48.317
2                          1755  137126        0 2016-06-14 04:02:02.359
3                          1954  144087        0 2016-06-14 04:02:17.346
4                          2065   55167        0 2016-06-14 04:02:25.546
...                         ...     ...      ...                     ...
87137                  12247748   82338        0 2016-06-23 15:04:12.080
87138                  12247898   75946        0 2016-06-23 15:04:18.922
87139                  12247968  510450        0 2016-06-23 15:04:22.462
87140                  12248263  210925        0 2016-06-23 15:04:35.983
87141                  12248331   99212        1 2016-06-23 15:04:39.661

[87142 rows x 4 columns]

In [6]:
# Add a pk for click table

data = pd.read_parquet(Path(data_dir) / 'data' / 'clicks.pqt')

In [7]:
data

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
0                            54  229333        0 2016-06-14 04:00:03.786
1                           668  211425        0 2016-06-14 04:00:48.317
2                          1755  137126        0 2016-06-14 04:02:02.359
3                          1954  144087        0 2016-06-14 04:02:17.346
4                          2065   55167        0 2016-06-14 04:02:25.546
...                         ...     ...      ...                     ...
87137                  12247748   82338        0 2016-06-23 15:04:12.080
87138                  12247898   75946        0 2016-06-23 15:04:18.922
87139                  12247968  510450        0 2016-06-23 15:04:22.462
87140                  12248263  210925        0 2016-06-23 15:04:35.983
87141                  12248331   99212        1 2016-06-23 15:04:39.661

[87142 rows x 4 columns]

In [8]:
data.iloc[19505]

display_id                      13532802
ad_id                             439186
clicked                                0
timestamp     2016-06-24 13:34:01.511000
Name: 19505, dtype: object

In [9]:
click_train = pd.read_parquet(Path(data_dir) / 'ctr' / 'train.pqt')
click_validation = pd.read_parquet(Path(data_dir) / 'ctr' / 'validation.pqt')
click_test = pd.read_parquet(Path(data_dir) / 'ctr' / 'test.pqt')

In [10]:
click_train

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
0                            54  229333        0 2016-06-14 04:00:03.786
1                           668  211425        0 2016-06-14 04:00:48.317
2                          1755  137126        0 2016-06-14 04:02:02.359
3                          1954  144087        0 2016-06-14 04:02:17.346
4                          2065   55167        0 2016-06-14 04:02:25.546
...                         ...     ...      ...                     ...
19501                  13532294   21395        0 2016-06-24 13:33:38.450
19502                  13532426  171379        0 2016-06-24 13:33:44.613
19503                  13532562  117128        0 2016-06-24 13:33:51.220
19504                  13532576  131410        0 2016-06-24 13:33:51.896
19505                  13532802  439186        0 2016-06-24 13:34:01.511

[69709 rows x 4 columns]

In [11]:
click_validation

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
19506                  13532941  140940        0 2016-06-24 13:34:07.240
19507                  13533223  515782        0 2016-06-24 13:34:20.049
19508                  13533450    5931        0 2016-06-24 13:34:30.411
19509                  13533686  220646        0 2016-06-24 13:34:40.712
19510                  13533787  290951        0 2016-06-24 13:34:45.278
...                         ...     ...      ...                     ...
28216                  15203012  497494        0 2016-06-25 19:48:10.278
28217                  15203190  270325        0 2016-06-25 19:48:21.915
28218                  15203196  123742        0 2016-06-25 19:48:22.461
28219                  15203263  470788        0 2016-06-25 19:48:26.373
28220                  15203281   73990        1 2016-06-25 19:48:27.524

[8715 rows x 4 columns]

In [12]:
click_test

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
28221                  15203286   34529        1 2016-06-25 19:48:27.896
28222                  15203442  175547        1 2016-06-25 19:48:37.116
28223                  15203733  141219        0 2016-06-25 19:48:57.735
28224                  15203916  149539        1 2016-06-25 19:49:08.246
28225                  15204236  171659        0 2016-06-25 19:49:29.654
...                         ...     ...      ...                     ...
36934                  16873764  101249        0 2016-06-27 03:59:01.278
36935                  16873924   78007        0 2016-06-27 03:59:12.542
36936                  16874020  547013        0 2016-06-27 03:59:19.733
36937                  16874085  289670        1 2016-06-27 03:59:24.419
36938                  16874135  276187        0 2016-06-27 03:59:28.067

[8718 rows x 4 columns]

In [13]:
# add a click_id column to the click table
click_train['click_id'] = click_train.index
click_validation['click_id'] = click_validation.index
click_test['click_id'] = click_test.index
click_train
click_validation
click_test

,display_id,ad_id,clicked,timestamp,click_id
__null_dask_index__,,,,,
28221,15203286,34529,1,2016-06-25 19:48:27.896,28221
28222,15203442,175547,1,2016-06-25 19:48:37.116,28222
28223,15203733,141219,0,2016-06-25 19:48:57.735,28223
28224,15203916,149539,1,2016-06-25 19:49:08.246,28224
28225,15204236,171659,0,2016-06-25 19:49:29.654,28225
...,...,...,...,...,...
36934,16873764,101249,0,2016-06-27 03:59:01.278,36934
36935,16873924,78007,0,2016-06-27 03:59:12.542,36935
36936,16874020,547013,0,2016-06-27 03:59:19.733,36936
36937,16874085,289670,1,2016-06-27 03:59:24.419,36937
36938,16874135,276187,0,2016-06-27 03:59:28.067,36938

In [14]:
data['click_id'] = data.index

In [15]:
data

,display_id,ad_id,clicked,timestamp,click_id
__null_dask_index__,,,,,
0,54,229333,0,2016-06-14 04:00:03.786,0
1,668,211425,0,2016-06-14 04:00:48.317,1
2,1755,137126,0,2016-06-14 04:02:02.359,2
3,1954,144087,0,2016-06-14 04:02:17.346,3
4,2065,55167,0,2016-06-14 04:02:25.546,4
...,...,...,...,...,...
87137,12247748,82338,0,2016-06-23 15:04:12.080,87137
87138,12247898,75946,0,2016-06-23 15:04:18.922,87138
87139,12247968,510450,0,2016-06-23 15:04:22.462,87139
87140,12248263,210925,0,2016-06-23 15:04:35.983,87140
87141,12248331,99212,1,2016-06-23 15:04:39.661,87141

In [16]:
# For other tables, we need to add a primary key column
PageView = pd.read_parquet(Path(data_dir) / 'data' / 'page_views.pqt')
PageView

,uuid,document_id,timestamp,platform,geo_location,traffic_source
__null_dask_index__,,,,,,
0,a082b2a5c44db2,7012,2016-06-14 13:28:59.757,1,GB>I2,2
1,be0066de7a0efb,25529,2016-06-14 12:33:54.261,1,US>MO>604,1
2,f006996a39d9da,25792,2016-06-14 19:54:55.694,1,US>DC>511,1
3,55aa1ee46a8529,25792,2016-06-14 14:13:44.442,1,US>CA,1
4,3482daa65621b9,25792,2016-06-14 20:36:38.879,1,US>PA>504,1
...,...,...,...,...,...,...
214395,e27eb50611c04f,488340,2016-06-15 04:19:14.142,2,US>VA>511,1
214396,d4dd7843511785,488340,2016-06-15 22:38:17.399,2,US>CA>807,1
214397,373412c3e0e58f,488340,2016-06-15 17:36:04.552,1,US>AL>686,1
214398,e20fd2d3523514,496504,2016-06-15 20:57:51.629,1,US>WA>819,1
214399,8930bdb94073f0,503198,2016-06-15 21:51:36.169,2,US>WA>819,1

In [17]:
pageview_id = np.arange(len(PageView))
pageview_id_map = pd.Series(pageview_id, index=PageView.index)
PageView['pageview_id'] = pageview_id_map
PageView

,uuid,document_id,timestamp,platform,geo_location,traffic_source,pageview_id
__null_dask_index__,,,,,,,
0,a082b2a5c44db2,7012,2016-06-14 13:28:59.757,1,GB>I2,2,0
1,be0066de7a0efb,25529,2016-06-14 12:33:54.261,1,US>MO>604,1,1
2,f006996a39d9da,25792,2016-06-14 19:54:55.694,1,US>DC>511,1,2
3,55aa1ee46a8529,25792,2016-06-14 14:13:44.442,1,US>CA,1,3
4,3482daa65621b9,25792,2016-06-14 20:36:38.879,1,US>PA>504,1,4
...,...,...,...,...,...,...,...
214395,e27eb50611c04f,488340,2016-06-15 04:19:14.142,2,US>VA>511,1,2034271
214396,d4dd7843511785,488340,2016-06-15 22:38:17.399,2,US>CA>807,1,2034272
214397,373412c3e0e58f,488340,2016-06-15 17:36:04.552,1,US>AL>686,1,2034273
214398,e20fd2d3523514,496504,2016-06-15 20:57:51.629,1,US>WA>819,1,2034274
214399,8930bdb94073f0,503198,2016-06-15 21:51:36.169,2,US>WA>819,1,2034275

In [18]:
DocumentsTopic = pd.read_parquet(Path(data_dir) / 'data' / 'documents_topics.pqt')
DocumentsTopic

                     document_id  topic_id  confidence_level
__null_dask_index__
0                        1380850        43          0.010575
1                        1359560       113          0.224327
2                         738820       260          0.355070
3                         667438       109          0.022044
4                         631963        25          0.016849
...                          ...       ...               ...
11321                    1436216       297          0.021160
11322                    1544426       298          0.010885
11323                    1956666       112          0.046848
11324                    2632899       239          0.016072
11325                    2698735        19          0.009430

[11326 rows x 3 columns]

In [19]:
documents_topic_id = np.arange(len(DocumentsTopic))
documents_topic_id_map = pd.Series(documents_topic_id, index=DocumentsTopic.index)
DocumentsTopic['documents_topic_id'] = documents_topic_id_map
DocumentsTopic

,document_id,topic_id,confidence_level,documents_topic_id
__null_dask_index__,,,,
0,1380850,43,0.010575,0
1,1359560,113,0.224327,1
2,738820,260,0.355070,2
3,667438,109,0.022044,3
4,631963,25,0.016849,4
...,...,...,...,...
11321,1436216,297,0.021160,11321
11322,1544426,298,0.010885,11322
11323,1956666,112,0.046848,11323
11324,2632899,239,0.016072,11324
11325,2698735,19,0.009430,11325

In [20]:
DocumentsCategory = pd.read_parquet(Path(data_dir) / 'data' / 'documents_categories.pqt')
DocumentsCategory
documents_category_id = np.arange(len(DocumentsCategory))
documents_category_id_map = pd.Series(documents_category_id, index=DocumentsCategory.index)
DocumentsCategory['documents_category_id'] = documents_category_id_map
DocumentsCategory

DocumentsEntity = pd.read_parquet(Path(data_dir) / 'data' / 'documents_entities.pqt')
DocumentsEntity
documents_entity_id = np.arange(len(DocumentsEntity))
documents_entity_id_map = pd.Series(documents_entity_id, index=DocumentsEntity.index)
DocumentsEntity['documents_entity_id'] = documents_entity_id_map
DocumentsEntity

,document_id,entity_id,confidence_level,documents_entity_id
__null_dask_index__,,,,
0,1539856,89ca77064645cfaa1b2bb7bf0e36bdec,0.237373,0
1,1443336,cf224ae861151ebd3274c0f2364ca73f,0.243289,1
2,1323061,bbaa46030aef98fe83b225ea914e0a24,0.564771,2
3,1366536,c7db8ad6e5d63811bb6ca7d9e94da01c,0.768865,3
4,1337221,0fa6266e7547f3714a43ad0e8d4a5774,0.257919,4
...,...,...,...,...
5533,1441869,2432e9e94eb36c73b09e84d6b99e48a1,0.636288,5533
5534,2366160,ab7743df6317a4f0329decfb03fd4a43,0.322837,5534
5535,2707833,ac33dad38c16a04e067fdcd33d0e6a6d,0.867834,5535
5536,2795659,84b3b036bb67c3e35dc521756611e5a8,0.215901,5536
5537,2676356,321b41b714d201d23348970be16e9118,0.357430,5537

In [26]:
# copy the whole folder to outbrain-small-griffin
import shutil
import os
# shutil.copytree(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small'), Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin'))
if os.path.exists(Path(griffin_data_dir)):
    shutil.rmtree(Path(griffin_data_dir))
shutil.copytree(Path(data_dir), Path(griffin_data_dir))

PosixPath('../griffin_datasets/outbrain-small-pk')

In [27]:
# change the click table in the new folder
# remove the old click table
shutil.rmtree(Path(griffin_data_dir) / 'ctr')
# create a new click table
Path(Path(griffin_data_dir) / 'ctr').mkdir(parents=True, exist_ok=True)
click_train.to_parquet(Path(griffin_data_dir) / 'ctr' / 'train.pqt')
click_validation.to_parquet(Path(griffin_data_dir) / 'ctr' / 'validation.pqt')
click_test.to_parquet(Path(griffin_data_dir) / 'ctr' / 'test.pqt')

In [29]:
# remove the old data file click.pqt
shutil.rmtree(Path(griffin_data_dir) / 'data' / 'clicks.pqt')
# add the new click table to the data folder
data.to_parquet(Path(griffin_data_dir) / 'data' / 'clicks.pqt')

In [31]:
# Save other tables
shutil.rmtree(Path(griffin_data_dir) / 'data' / 'page_views.pqt')
PageView.to_parquet(Path(griffin_data_dir) / 'data' / 'page_views.pqt')
shutil.rmtree(Path(griffin_data_dir) / 'data' / 'documents_topics.pqt')
DocumentsTopic.to_parquet(Path(griffin_data_dir) / 'data' / 'documents_topics.pqt')
shutil.rmtree(Path(griffin_data_dir) / 'data' / 'documents_categories.pqt')
DocumentsCategory.to_parquet(Path(griffin_data_dir) / 'data' / 'documents_categories.pqt')
shutil.rmtree(Path(griffin_data_dir) / 'data' / 'documents_entities.pqt')
DocumentsEntity.to_parquet(Path(griffin_data_dir) / 'data' / 'documents_entities.pqt')

In [16]:
# manually save the metadata file

dataset_name: outbrain-small
tables:
  - name: Event
    source: data/events.pqt
    format: parquet
    columns:
      - name: display_id
        dtype: primary_key
      - name: uuid
        dtype: foreign_key
        link_to: User.uuid
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: platform
        dtype: category
      - name: timestamp
        dtype: datetime
      - name: geo_location
        dtype: category
    time_column: timestamp
  - name: Pageview
    source: data/page_views.pqt
    format: parquet
    columns:
      - name: pageview_id
        dtype: primary_key
      - name: uuid
        dtype: foreign_key
        link_to: User.uuid
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: timestamp
        dtype: datetime
      - name: platform
        dtype: category
      - name: geo_location
        dtype: category
      - name: traffic_source
        dtype: category
    time_column: timestamp
  - name: Click
    source: data/clicks.pqt
    format: parquet
    columns:
      - name: click_id
        dtype: primary_key
      - name: display_id
        dtype: foreign_key
        link_to: Event.display_id
      - name: ad_id
        dtype: foreign_key
        link_to: PromotedContent.ad_id
      - name: clicked
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: PromotedContent
    source: data/promoted_content.pqt
    format: parquet
    columns:
      - name: ad_id
        dtype: primary_key
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: campaign_id
        dtype: category
      - name: advertiser_id
        dtype: category
  - name: DocumentsMeta
    source: data/documents_meta.pqt
    format: parquet
    columns:
      - name: document_id
        dtype: primary_key
      - name: source_id
        dtype: category
      - name: publisher_id
        dtype: category
      - name: publish_time
        dtype: datetime
    time_column: publish_time
  - name: DocumentsTopic
    source: data/documents_topics.pqt
    format: parquet
    columns:
      - name: documents_topic_id
        dtype: primary_key
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: topic_id
        dtype: category
      - name: confidence_level
        dtype: float
  - name: DocumentsCategory
    source: data/documents_categories.pqt
    format: parquet
    columns:
      - name: documents_category_id
        dtype: primary_key
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: category_id
        dtype: category
      - name: confidence_level
        dtype: float
  - name: DocumentsEntity
    source: data/documents_entities.pqt
    format: parquet
    columns:
      - name: documents_entity_id
        dtype: primary_key
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: entity_id
        dtype: category
      - name: confidence_level
        dtype: float
tasks:
  - name: ctr
    source: ctr/{split}.pqt
    format: parquet
    columns:
      - name: click_id
        dtype: primary_key
      - name: display_id
        dtype: foreign_key
        link_to: Event.display_id
      - name: ad_id
        dtype: foreign_key
        link_to: PromotedContent.ad_id
      - name: clicked
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
    evaluation_metric: auroc
    target_column: clicked
    target_table: Click
    task_type: classification