In [1]:
import os
import numpy as np
import pandas as pd
import shutil
from pathlib import Path

In [4]:
data_dir = Path('../griffin_datasets/tel-griffin-v3')
griffin_data_dir = Path('../griffin_datasets/tel-pk')

In [7]:
severity_type = pd.read_parquet(data_dir / 'severity.pqt')
severity_type['primary_key'] = severity_type.index
severity_type

         id    severity_type  primary_key
0      6597  severity_type 2            0
1      8011  severity_type 2            1
2      2597  severity_type 2            2
3      5022  severity_type 1            3
4      6852  severity_type 1            4
...     ...              ...          ...
18547  3761  severity_type 1        18547
18548  8720  severity_type 1        18548
18549  6488  severity_type 2        18549
18550   878  severity_type 2        18550
18551  4464  severity_type 1        18551

[18552 rows x 3 columns]

In [11]:
event_type = pd.read_parquet(data_dir / 'event.pqt')
event_type['primary_key'] = event_type.index
event_type

         id     event_type  primary_key
0      6597  event_type 11            0
1      8011  event_type 15            1
2      2597  event_type 15            2
3      5022  event_type 15            3
4      5022  event_type 11            4
...     ...            ...          ...
31165  3761  event_type 11        31165
31166  8720  event_type 11        31166
31167  6488  event_type 11        31167
31168   878  event_type 11        31168
31169  4464  event_type 11        31169

[31170 rows x 3 columns]

In [12]:
resource_type = pd.read_parquet(data_dir / 'resource.pqt')
resource_type['primary_key'] = resource_type.index
resource_type

         id    resource_type  primary_key
0      6597  resource_type 8            0
1      8011  resource_type 8            1
2      2597  resource_type 8            2
3      5022  resource_type 8            3
4      6852  resource_type 8            4
...     ...              ...          ...
21071  3761  resource_type 8        21071
21072  8720  resource_type 8        21072
21073  6488  resource_type 8        21073
21074   878  resource_type 8        21074
21075  4464  resource_type 8        21075

[21076 rows x 3 columns]

In [14]:
log_feature = pd.read_parquet(data_dir / 'feature.pqt')
log_feature['primary_key'] = log_feature.index
log_feature

         id  log_feature  volume  primary_key
0      6597   feature 68       6            0
1      8011   feature 68       7            1
2      2597   feature 68       1            2
3      5022  feature 172       2            3
4      5022   feature 56       1            4
...     ...          ...     ...          ...
58666  8720  feature 209       1        58666
58667  6488   feature 54       3        58667
58668   878   feature 62       1        58668
58669  4464  feature 209       1        58669
58670  4464   feature 87       2        58670

[58671 rows x 4 columns]

In [15]:
# Saving the files
shutil.copytree(data_dir, griffin_data_dir)
severity_type.to_parquet(griffin_data_dir / 'severity.pqt')
event_type.to_parquet(griffin_data_dir / 'event.pqt')
resource_type.to_parquet(griffin_data_dir / 'resource.pqt')
log_feature.to_parquet(griffin_data_dir / 'feature.pqt')

dataset_name: telstra
tables:
  - name: Event
    source: location.pqt
    format: parquet
    columns:
    - name: id
      dtype: primary_key
    - name: location
      dtype: category
  - name: Severity_type
    source: severity.pqt
    format: parquet
    columns:
    - name: primary_key
      dtype: primary_key
    - name: id
      dtype: foreign_key
      link_to: Event.id
    - name: severity_type
      dtype: category
  - name: Event_type
    source: event.pqt
    format: parquet
    columns:
    - name: primary_key
      dtype: primary_key
    - name: id
      dtype: foreign_key
      link_to: Event.id
    - name: event_type
      dtype: category
  - name: Resource_type
    source: resource.pqt
    format: parquet
    columns:
    - name: primary_key
      dtype: primary_key
    - name: id
      dtype: foreign_key
      link_to: Event.id
    - name: resource_type
      dtype: category
  - name: Log_feature
    source: feature.pqt
    format: parquet
    columns:
    - name: primary_key
      dtype: primary_key
    - name: id
      dtype: foreign_key
      link_to: Event.id
    - name: log_feature
      dtype: category
    - name: volume
      dtype: float
tasks:
  - name: severity
    source: severity/{split}.pqt
    format: parquet
    columns:
      - name: id
        dtype: primary_key
      - name: location
        dtype: category
      - name: fault_severity
        dtype: category
    time_column: null
    evaluation_metric: logloss
    target_column: fault_severity
    target_table: Event
    task_type: classification