In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
data_dir = Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small')

In [3]:
clicks = pd.read_parquet(data_dir / 'data' / 'clicks.pqt')
print(clicks.shape)
clicks

(87142, 4)

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
0                            54  229333        0 2016-06-14 04:00:03.786
1                           668  211425        0 2016-06-14 04:00:48.317
2                          1755  137126        0 2016-06-14 04:02:02.359
3                          1954  144087        0 2016-06-14 04:02:17.346
4                          2065   55167        0 2016-06-14 04:02:25.546
...                         ...     ...      ...                     ...
87137                  12247748   82338        0 2016-06-23 15:04:12.080
87138                  12247898   75946        0 2016-06-23 15:04:18.922
87139                  12247968  510450        0 2016-06-23 15:04:22.462
87140                  12248263  210925        0 2016-06-23 15:04:35.983
87141                  12248331   99212        1 2016-06-23 15:04:39.661

[87142 rows x 4 columns]

In [4]:
# Add a pk for click table

data = pd.read_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small/data/clicks.pqt'))

In [5]:
data

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
0                            54  229333        0 2016-06-14 04:00:03.786
1                           668  211425        0 2016-06-14 04:00:48.317
2                          1755  137126        0 2016-06-14 04:02:02.359
3                          1954  144087        0 2016-06-14 04:02:17.346
4                          2065   55167        0 2016-06-14 04:02:25.546
...                         ...     ...      ...                     ...
87137                  12247748   82338        0 2016-06-23 15:04:12.080
87138                  12247898   75946        0 2016-06-23 15:04:18.922
87139                  12247968  510450        0 2016-06-23 15:04:22.462
87140                  12248263  210925        0 2016-06-23 15:04:35.983
87141                  12248331   99212        1 2016-06-23 15:04:39.661

[87142 rows x 4 columns]

In [6]:
data.iloc[19505]

display_id                      13532802
ad_id                             439186
clicked                                0
timestamp     2016-06-24 13:34:01.511000
Name: 19505, dtype: object

In [7]:
click_train = pd.read_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small/ctr/train.pqt'))
click_validation = pd.read_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small/ctr/validation.pqt'))
click_test = pd.read_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small/ctr/test.pqt'))

In [8]:
click_train

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
0                            54  229333        0 2016-06-14 04:00:03.786
1                           668  211425        0 2016-06-14 04:00:48.317
2                          1755  137126        0 2016-06-14 04:02:02.359
3                          1954  144087        0 2016-06-14 04:02:17.346
4                          2065   55167        0 2016-06-14 04:02:25.546
...                         ...     ...      ...                     ...
19501                  13532294   21395        0 2016-06-24 13:33:38.450
19502                  13532426  171379        0 2016-06-24 13:33:44.613
19503                  13532562  117128        0 2016-06-24 13:33:51.220
19504                  13532576  131410        0 2016-06-24 13:33:51.896
19505                  13532802  439186        0 2016-06-24 13:34:01.511

[69709 rows x 4 columns]

In [9]:
click_validation

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
19506                  13532941  140940        0 2016-06-24 13:34:07.240
19507                  13533223  515782        0 2016-06-24 13:34:20.049
19508                  13533450    5931        0 2016-06-24 13:34:30.411
19509                  13533686  220646        0 2016-06-24 13:34:40.712
19510                  13533787  290951        0 2016-06-24 13:34:45.278
...                         ...     ...      ...                     ...
28216                  15203012  497494        0 2016-06-25 19:48:10.278
28217                  15203190  270325        0 2016-06-25 19:48:21.915
28218                  15203196  123742        0 2016-06-25 19:48:22.461
28219                  15203263  470788        0 2016-06-25 19:48:26.373
28220                  15203281   73990        1 2016-06-25 19:48:27.524

[8715 rows x 4 columns]

In [10]:
click_test

                     display_id   ad_id  clicked               timestamp
__null_dask_index__
28221                  15203286   34529        1 2016-06-25 19:48:27.896
28222                  15203442  175547        1 2016-06-25 19:48:37.116
28223                  15203733  141219        0 2016-06-25 19:48:57.735
28224                  15203916  149539        1 2016-06-25 19:49:08.246
28225                  15204236  171659        0 2016-06-25 19:49:29.654
...                         ...     ...      ...                     ...
36934                  16873764  101249        0 2016-06-27 03:59:01.278
36935                  16873924   78007        0 2016-06-27 03:59:12.542
36936                  16874020  547013        0 2016-06-27 03:59:19.733
36937                  16874085  289670        1 2016-06-27 03:59:24.419
36938                  16874135  276187        0 2016-06-27 03:59:28.067

[8718 rows x 4 columns]

In [11]:
# add a click_id column to the click table
click_train['click_id'] = click_train.index
click_validation['click_id'] = click_validation.index
click_test['click_id'] = click_test.index
click_train
click_validation
click_test

,display_id,ad_id,clicked,timestamp,click_id
__null_dask_index__,,,,,
28221,15203286,34529,1,2016-06-25 19:48:27.896,28221
28222,15203442,175547,1,2016-06-25 19:48:37.116,28222
28223,15203733,141219,0,2016-06-25 19:48:57.735,28223
28224,15203916,149539,1,2016-06-25 19:49:08.246,28224
28225,15204236,171659,0,2016-06-25 19:49:29.654,28225
...,...,...,...,...,...
36934,16873764,101249,0,2016-06-27 03:59:01.278,36934
36935,16873924,78007,0,2016-06-27 03:59:12.542,36935
36936,16874020,547013,0,2016-06-27 03:59:19.733,36936
36937,16874085,289670,1,2016-06-27 03:59:24.419,36937
36938,16874135,276187,0,2016-06-27 03:59:28.067,36938

In [7]:
data['click_id'] = data.index

In [8]:
data

,display_id,ad_id,clicked,timestamp,click_id
__null_dask_index__,,,,,
0,54,229333,0,2016-06-14 04:00:03.786,0
1,668,211425,0,2016-06-14 04:00:48.317,1
2,1755,137126,0,2016-06-14 04:02:02.359,2
3,1954,144087,0,2016-06-14 04:02:17.346,3
4,2065,55167,0,2016-06-14 04:02:25.546,4
...,...,...,...,...,...
87137,12247748,82338,0,2016-06-23 15:04:12.080,87137
87138,12247898,75946,0,2016-06-23 15:04:18.922,87138
87139,12247968,510450,0,2016-06-23 15:04:22.462,87139
87140,12248263,210925,0,2016-06-23 15:04:35.983,87140
87141,12248331,99212,1,2016-06-23 15:04:39.661,87141

In [13]:
# copy the whole folder to outbrain-small-griffin
import shutil
shutil.copytree(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small'), Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin'))

PosixPath('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin')

In [14]:
# change the click table in the new folder
# remove the old click table
shutil.rmtree(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin/ctr'))
# create a new click table
Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin/ctr').mkdir(parents=True, exist_ok=True)
click_train.to_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin/ctr/train.pqt'))
click_validation.to_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin/ctr/validation.pqt'))
click_test.to_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin/ctr/test.pqt'))

In [15]:
# remove the old data file click.pqt
shutil.rmtree(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin/data/clicks.pqt'))
# add the new click table to the data folder
data.to_parquet(Path('/home/ubuntu/Griffin_pure/griffin_datasets/outbrain-small-griffin/data/clicks.pqt'))

In [16]:
# manually save the metadata file

dataset_name: outbrain-small
tables:
  - name: Event
    source: data/events.pqt
    format: parquet
    columns:
      - name: display_id
        dtype: primary_key
      - name: uuid
        dtype: foreign_key
        link_to: User.uuid
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: platform
        dtype: category
      - name: timestamp
        dtype: datetime
      - name: geo_location
        dtype: category
    time_column: timestamp
  - name: Pageview
    source: data/page_views.pqt
    format: parquet
    columns:
      - name: uuid
        dtype: foreign_key
        link_to: User.uuid
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: timestamp
        dtype: datetime
      - name: platform
        dtype: category
      - name: geo_location
        dtype: category
      - name: traffic_source
        dtype: category
    time_column: timestamp
  - name: Click
    source: data/clicks.pqt
    format: parquet
    columns:
      - name: click_id
        dtype: primary_key
      - name: display_id
        dtype: foreign_key
        link_to: Event.display_id
      - name: ad_id
        dtype: foreign_key
        link_to: PromotedContent.ad_id
      - name: clicked
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
  - name: PromotedContent
    source: data/promoted_content.pqt
    format: parquet
    columns:
      - name: ad_id
        dtype: primary_key
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: campaign_id
        dtype: category
      - name: advertiser_id
        dtype: category
  - name: DocumentsMeta
    source: data/documents_meta.pqt
    format: parquet
    columns:
      - name: document_id
        dtype: primary_key
      - name: source_id
        dtype: category
      - name: publisher_id
        dtype: category
      - name: publish_time
        dtype: datetime
    time_column: publish_time
  - name: DocumentsTopic
    source: data/documents_topics.pqt
    format: parquet
    columns:
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: topic_id
        dtype: category
      - name: confidence_level
        dtype: float
  - name: DocumentsCategory
    source: data/documents_categories.pqt
    format: parquet
    columns:
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: category_id
        dtype: category
      - name: confidence_level
        dtype: float
  - name: DocumentsEntity
    source: data/documents_entities.pqt
    format: parquet
    columns:
      - name: document_id
        dtype: foreign_key
        link_to: DocumentsMeta.document_id
      - name: entity_id
        dtype: category
      - name: confidence_level
        dtype: float
tasks:
  - name: ctr
    source: ctr/{split}.pqt
    format: parquet
    columns:
      - name: click_id
        dtype: primary_key
      - name: display_id
        dtype: foreign_key
        link_to: Event.display_id
      - name: ad_id
        dtype: foreign_key
        link_to: PromotedContent.ad_id
      - name: clicked
        dtype: category
      - name: timestamp
        dtype: datetime
    time_column: timestamp
    evaluation_metric: auroc
    target_column: clicked
    target_table: Click
    task_type: classification