In [1]:
import os
from pathlib import Path
import shutil
import pandas as pd
import numpy as np

data_dir = Path('../datasets/stackexchange')
griffin_data_dir = Path('../griffin_datasets/stackexchange-pk')

In [2]:
# read the postTags table
postTags = pd.read_parquet(Path(data_dir) / 'data' / 'postTags.pqt')
postTags

        PostId  TagId
0            1      1
1            1      2
2            1      3
3            2      6
4            2   3822
...        ...    ...
648572  625557    111
648573  625557      9
648574  625557     62
648575  625557   1579
648576  625557   4293

[648577 rows x 2 columns]

In [3]:
# Add a new column 'post_tag_id' to the postTags table
postTags['post_tag_id'] = np.arange(len(postTags))
postTags

        PostId  TagId  post_tag_id
0            1      1            0
1            1      2            1
2            1      3            2
3            2      6            3
4            2   3822            4
...        ...    ...          ...
648572  625557    111       648572
648573  625557      9       648573
648574  625557     62       648574
648575  625557   1579       648575
648576  625557   4293       648576

[648577 rows x 3 columns]

In [4]:
# Save the whole datasets to the griffin_data_dir
shutil.copytree(Path(data_dir), Path(griffin_data_dir))

# Save the postTags table to the griffin_data_dir
postTags.to_parquet(Path(griffin_data_dir) / 'data' / 'postTags.pqt')

column_groups: null
dataset_name: stackexchange
tables:
- columns:
  - dtype: primary_key
    name: Id
  - dtype: category
    name: Class
  - dtype: datetime
    name: Date
  - dtype: text
    name: Name
  - dtype: category
    name: TagBased
  - dtype: foreign_key
    link_to: Users.Id
    name: UserId
  format: parquet
  name: Badges
  source: data/badges.pqt
  time_column: Date
- columns:
  - dtype: primary_key
    name: Id
  - dtype: datetime
    name: CreationDate
  - dtype: text
    name: Text
  - dtype: foreign_key
    link_to: Posts.Id
    name: PostId
  - dtype: foreign_key
    link_to: Users.Id
    name: UserId
  format: parquet
  name: Comments
  source: data/comments.pqt
  time_column: CreationDate
- columns:
  - dtype: primary_key
    name: Id
  - dtype: text
    name: Comment
  - dtype: datetime
    name: CreationDate
  - dtype: category
    name: PostHistoryTypeId
  - dtype: text
    name: Text
  - dtype: foreign_key
    link_to: Posts.Id
    name: PostId
  - dtype: foreign_key
    link_to: Users.Id
    name: UserId
  format: parquet
  name: PostHistory
  source: data/postHistory.pqt
  time_column: CreationDate
- columns:
  - dtype: primary_key
    name: Id
  - dtype: datetime
    name: CreationDate
  - dtype: category
    name: LinkTypeId
  - dtype: foreign_key
    link_to: Posts.Id
    name: PostId
  - dtype: foreign_key
    link_to: Posts.Id
    name: RelatedPostId
  format: parquet
  name: PostLink
  source: data/postLinks.pqt
  time_column: CreationDate
- columns:
  - dtype: primary_key
    name: post_tag_id
  - dtype: foreign_key
    link_to: Posts.Id
    name: PostId
  - dtype: foreign_key
    link_to: Tag.Id
    name: TagId
  format: parquet
  name: PostTag
  source: data/postTags.pqt
  time_column: null
- columns:
  - dtype: primary_key
    name: Id
  - dtype: text
    name: Body
  - dtype: datetime
    name: CreationDate
  - dtype: category
    name: PostTypeId
  - dtype: text
    name: Title
  - dtype: foreign_key
    link_to: Posts.Id
    name: AcceptedAnswerId
  - dtype: foreign_key
    link_to: Users.Id
    name: LastEditorUserId
  - dtype: foreign_key
    link_to: Users.Id
    name: OwnerUserId
  - dtype: foreign_key
    link_to: Posts.Id
    name: ParentId
  format: parquet
  name: Posts
  source: data/posts.pqt
  time_column: CreationDate
- columns:
  - dtype: primary_key
    name: Id
  - dtype: text
    name: TagName
  - dtype: foreign_key
    link_to: Posts.Id
    name: ExcerptPostId
  - dtype: foreign_key
    link_to: Posts.Id
    name: WikiPostId
  format: parquet
  name: Tag
  source: data/tags.pqt
  time_column: null
- columns:
  - dtype: primary_key
    name: Id
  - dtype: text
    name: AboutMe
  - dtype: datetime
    name: CreationDate
  - dtype: text
    name: Location
  format: parquet
  name: Users
  source: data/users.pqt
  time_column: CreationDate
- columns:
  - dtype: primary_key
    name: Id
  - dtype: category
    name: BountyAmount
  - dtype: datetime
    name: CreationDate
  - dtype: category
    name: VoteTypeId
  - dtype: foreign_key
    link_to: Posts.Id
    name: PostId
  - dtype: foreign_key
    link_to: Users.Id
    name: UserId
  format: parquet
  name: Vote
  source: data/votes.pqt
  time_column: CreationDate
tasks:
- columns:
  - dtype: primary_key
    name: Id
  - dtype: datetime
    name: Timestamp
  - dtype: category
    name: Target
  evaluation_metric: auroc
  format: parquet
  key_prediction_label_column: label
  key_prediction_query_idx_column: query_idx
  name: churn
  source: churn/target_churn_{split}.pqt
  target_column: Target
  target_table: Users
  task_type: classification
  time_column: Timestamp
- columns:
  - dtype: primary_key
    name: Id
  - dtype: datetime
    name: CreationDate
  - dtype: category
    name: Target
  evaluation_metric: auroc
  format: parquet
  key_prediction_label_column: label
  key_prediction_query_idx_column: query_idx
  name: upvote
  source: upvote/target_upvote2_cls_{split}.pqt
  target_column: Target
  target_table: Posts
  task_type: classification
  time_column: CreationDate